[#ftl]
[#-- @implicitly included --]
[#-- @ftlvariable name="" type="ru.itmo.web.lesson4.model.User.Color" file="../webapp/WEB-INF/templates/common.ftlh" --]
[#-- @ftlvariable name="post_id" type="long" --]
[#-- @ftlvariable name="user_id" type="long" --]
[#-- @ftlvariable name="posts" type="ru.itmo.web.lesson4.model.Post[]" --]
[#-- @ftlvariable name="post" type="ru.itmo.web.lesson4.model.Post" --]
[#-- @ftlvariable name="href" type="java.lang.String" --]
[#-- @ftlvariable name="users" type="ru.itmo.web.lesson4.model.User[]" --]
[#-- @ftlvariable name="user" type="ru.itmo.web.lesson4.model.User" --]
